"use client";

import { useCallback, useEffect, useState } from "react";
import { useWorkspaceData } from "@/components/workspace-data";

type Recommendation = {
  id: string;
  equipment_id: string;
  text: string;
  status: "GENERATED" | "REVIEWED" | "ACCEPTED" | "REJECTED" | "EXPIRED";
  expected_benefit: Record<string, number> | null;
  energy_impact: { change_kw?: number; baseline_kw?: number; scenario_kw?: number } | null;
  proposed_change: { temperature_c?: number; pressure_bar?: number; flow_m3_h?: number } | null;
  constraint_status: string | null;
  confidence: string;
  expires_at: string | null;
  timestamp: string;
  advisory: string;
};

const DECISIONS = ["REVIEWED", "ACCEPTED", "REJECTED"] as const;

function number(value: number | undefined | null, digits = 1) {
  return value === undefined || value === null ? "—" : value.toFixed(digits);
}

export default function Recommendations() {
  const { apiFetch, isLoading: workspaceLoading } = useWorkspaceData();
  const [items, setItems] = useState<Recommendation[]>([]);
  const [loading, setLoading] = useState(true);
  const [busyId, setBusyId] = useState("");
  const [error, setError] = useState("");
  const [message, setMessage] = useState("");
  const [commentFor, setCommentFor] = useState("");

  const load = useCallback(async () => {
    setLoading(true);
    setError("");
    try {
      const response = await apiFetch("/api/v1/recommendations?limit=100");
      if (!response.ok) throw new Error(`Unable to load recommendations (HTTP ${response.status}).`);
      const body = (await response.json()) as { items?: Recommendation[] };
      setItems(body.items ?? []);
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Unable to load recommendations.");
    } finally {
      setLoading(false);
    }
  }, [apiFetch]);

  useEffect(() => { void load(); }, [load]);

  async function review(id: string, decision: (typeof DECISIONS)[number], comment: string) {
    setBusyId(id);
    setError("");
    setMessage("");
    try {
      const response = await apiFetch(`/api/v1/recommendations/${id}/review`, { json: { decision, comment } });
      const body = (await response.json()) as { error?: { message?: string }; detail?: { message?: string } | string };
      if (!response.ok) {
        const detail = body.detail;
        throw new Error(typeof detail === "string" ? detail : detail?.message ?? body.error?.message ?? "Review failed.");
      }
      setMessage(`Recommendation recorded as ${decision}. The decision is stored in the audit log.`);
      setCommentFor("");
      await load();
    } catch (caught) {
      setError(caught instanceof Error ? caught.message : "Review failed.");
    } finally {
      setBusyId("");
    }
  }

  if (workspaceLoading || (loading && items.length === 0 && !error)) {
    return <div className="console-loading" role="status">Loading recommendations…</div>;
  }

  return (
    <div className="recommendations-view">
      <p className="notice">
        Recommendations are advisory outputs of validated model analysis. A human must review them against
        operating procedures; ProcessTwin never sends a control command to the plant.
      </p>
      {message && <p className="message" role="status">{message}</p>}
      {error && <div className="error-state" role="alert"><strong>Request failed.</strong> {error}</div>}
      <section className="panel">
        <div className="panel-title">
          <div>
            <p className="eyebrow">ADVISORY QUEUE</p>
            <h2>Recommendations</h2>
          </div>
          <button type="button" className="secondary" onClick={() => void load()} disabled={loading}>
            {loading ? "Refreshing…" : "Refresh"}
          </button>
        </div>
        {items.length === 0 && !error ? (
          <div className="empty-state">
            <h2>No recommendations yet</h2>
            <p>Recommendations are generated by bounded optimization runs against a validated model. Complete the model lifecycle in Models, then run an optimization for this equipment.</p>
          </div>
        ) : (
          <div className="table-wrap">
            <table>
              <thead>
                <tr>
                  <th>Recommendation</th>
                  <th>Proposed operating point</th>
                  <th>Expected impact</th>
                  <th>Status</th>
                  <th>Created</th>
                  <th>Review</th>
                </tr>
              </thead>
              <tbody>
                {items.map((item) => (
                  <tr key={item.id}>
                    <td>
                      <strong>{item.text}</strong>
                      <small>{item.confidence}</small>
                    </td>
                    <td>
                      {item.proposed_change
                        ? `${number(item.proposed_change.temperature_c)} °C · ${number(item.proposed_change.pressure_bar)} bar · ${number(item.proposed_change.flow_m3_h)} m³/h`
                        : "—"}
                    </td>
                    <td>
                      {item.expected_benefit?.yield_percentage_points !== undefined
                        ? `${item.expected_benefit.yield_percentage_points >= 0 ? "+" : ""}${number(item.expected_benefit.yield_percentage_points)} pp yield`
                        : "—"}
                      {item.energy_impact?.change_kw !== undefined && (
                        <small>{number(item.energy_impact.change_kw)} kW energy</small>
                      )}
                    </td>
                    <td><span className={`pill ${item.status === "ACCEPTED" ? "good" : ""}`}>{item.status}</span></td>
                    <td>{new Date(item.timestamp).toLocaleString()}</td>
                    <td>
                      {["GENERATED", "REVIEWED"].includes(item.status) ? (
                        commentFor === item.id ? (
                          <form
                            onSubmit={(event) => {
                              event.preventDefault();
                              const form = new FormData(event.currentTarget);
                              const comment = String(form.get("comment") ?? "").trim();
                              if (comment.length < 5) { setError("A review comment of at least 5 characters is required."); return; }
                              void review(item.id, (form.get("decision") as (typeof DECISIONS)[number]) ?? "REVIEWED", comment);
                            }}
                            className="import-form"
                          >
                            <label>
                              Decision
                              <select name="decision" defaultValue="REVIEWED">
                                {DECISIONS.map((decision) => <option key={decision} value={decision}>{decision}</option>)}
                              </select>
                            </label>
                            <label>
                              Review comment
                              <input name="comment" required minLength={5} maxLength={2000} placeholder="Reviewed against operating procedures and envelope." />
                            </label>
                            <button type="submit" disabled={busyId === item.id}>Record review</button>
                            <button type="button" className="secondary" onClick={() => setCommentFor("")}>Cancel</button>
                          </form>
                        ) : (
                          <button type="button" className="secondary" onClick={() => setCommentFor(item.id)}>Review…</button>
                        )
                      ) : (
                        "—"
                      )}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </section>
    </div>
  );
}
